- type: entity
  parent: MarkerBase
  id: HeadRevolutionaryBriefcaseSpawner
  categories: [ HideSpawnMenu ]
  components:
  - type: EntityTableSpawner
    table: !type:AllSelector
      children:
      - id: HeadRevolutionaryBriefcase
      - id: RedspaceLifeline

- type: entity
  parent: CybersunBriefcase
  id: HeadRevolutionaryBriefcase
  suffix: Do Not Map
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: Flash
        - id: ClothingEyesGlassesSunglasses
